# 日志配置
#logging:
#    config: classpath:logback.xml
#druid:
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password: 123456
#    initial-size: 1
#    min-idle: 1
#    max-active: 20
#    test-on-borrow: true
#spring:
#    #数据源
#  datasource:
#    url: jdbc:mysql://localhost:3306/test??useUnicode=true&amp;characterEncoding=UTF-8
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
#  messages:
#    basename: i18n/lang
#    encoding: UTF-8
server:
      port: 8087
spring: 
  redis:                                             # redis连接配置
    host: localhost
    password: 
    port: 6379
    jedis:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 100
        max-wait: -1
#mybatis:
#    config-location: classpath:mybatis-config.xml
#    mapper-locations: classpath*:mapper/*.xml, classpath*:mapper/*/*.xml
